import random
import requests
import os
import re
import time
import copy
import logging
import concurrent.futures
import os

logger = logging.getLogger(__file__)
logger.setLevel(logging.INFO)

URL = os.environ.get("LLM_EVALUATOR_URL", "http://localhost:30000/v1/chat/completions")
NO_REPLY_STR = 'NO REPLY'
API_KEY = os.environ.get("LLM_EVALUATOR_API_KEY", None)
MODEL = os.environ.get("LLM_EVALUATOR_MODEL", "Qwen/Qwen3-32B")
MODEL_REPETITION = os.environ.get("LLM_EVALUATOR_MODEL_REPETITION", MODEL)
MAX_SCORES = int(os.environ.get("LLM_EVALUATOR_MAX_SCORES", 5))
PAUC_ADD_PREV_TURNS = int(os.environ.get("LLM_EVALUATOR_PAUC_ADD_PREV_TURNS", 0))  # if or not add prev replies in the same ground truth reply span when calculating similarity
REPETITION_IN_ALL_SPANS = int(os.environ.get("LLM_EVALUATOR_REPETITION_IN_ALL_SPANS", 1))   # if or not add prev replies in previous ground truth reply spans when calculating repetition

PAUC_WEIGHT = float(os.environ.get("LLM_EVALUATOR_PAUC_WEIGHT", 3))
REPETITION_WEIGHT = float(os.environ.get("LLM_EVALUATOR_REPETITION_WEIGHT", 3))
OUTSPAN_WEIGHT = float(os.environ.get("LLM_EVALUATOR_OUTSPAN_WEIGHT", 2))
COMMON_PREFIX_WEIGHT = float(os.environ.get("LLM_EVALUATOR_COMMON_PREFIX_WEIGHT", 0))
COMMON_PREFIX_THRES = float(os.environ.get("LLM_EVALUATOR_COMMON_PREFIX_THRES", 50))

logger.info(f"reward function info: {MODEL=}, {MODEL_REPETITION=}, {URL=}, {MAX_SCORES=}, {PAUC_ADD_PREV_TURNS=}, {REPETITION_IN_ALL_SPANS=}, {COMMON_PREFIX_THRES=}")
logger.info(f"{PAUC_WEIGHT=}, {REPETITION_WEIGHT=}, {OUTSPAN_WEIGHT=}, {COMMON_PREFIX_WEIGHT=}")


similarity_instruction_3scores = (
    "You are an evaluator for a video question answering system. Your task is to rate the whether the predicted answer covers the key points of the ground truth answer. Use the following scale to assign a score:\n"
    "- 3: Mostly covered; the predicted answer covers all key information in the ground truth answer, though it may have minor inaccuracies or rephrases.\n"
    "- 2: Partially covered; the predicted answer has some correct information, but also contains significant inaccuracies or missing key points.\n"
    "- 1: Incorrect; the predicted answer may be related to the ground truth answer, but most of the information is missing, or the predicted answer is not relevant to the question or in very poor quality.\n"
    "Output the score only, do not add more explanations."
)

similarity_instruction_5scores = (
    "You are an evaluator for a video question answering system. Your task is to rate whether the predicted answer covers the key points of the ground truth answer. Use the following scale to assign a score:\n"
    "- 5: Fully covered; the predicted answer covers all key information in the ground truth answer with no significant inaccuracies or rephrasing.\n"
    "- 4: Mostly covered; the predicted answer covers all key information but may have minor inaccuracies or rephrasing.\n"
    "- 3: Partially covered; the predicted answer includes some correct information but is missing key points or has significant inaccuracies.\n"
    "- 2: Largely incorrect; the predicted answer contains some relevant information but is mostly inaccurate or irrelevant.\n"
    "- 1: Incorrect; the predicted answer is either not relevant to the question or very poor in quality.\n"
    "Output the score only, do not add more explanations."
)

similarity_instruction = {
    3: similarity_instruction_3scores,
    5: similarity_instruction_5scores
}

repetition_instruction = (
    "You are an evaluator for a multi-turn video question answering system. Your task is to judge whether a new reply generated by the model is repetitive (all its information is already convered by previous turns) or not.\n"
    "Output \"yes\" if all information in the new turn is already covered by previous turns. Output \"no\" if there is new information in the new turn.\n"
    "Only reply with \"yes\" or \"no\". Do not add any more explainations."
)

has_any_repetition_instruction = (
    "You are an evaluator for a multi-turn video question answering system. Your task is to judge whether a new reply generated by the model has some content that repeats the previous turns.\n"
    "Output \"yes\" if some of the content in this turn is repeating the previous turns. Output \"no\" if all the information in this turn is substantially different from the previous turns.\n"
    "Only reply with \"yes\" or \"no\". Do not add any more explainations."
)


def send_request(model_input, instruction, model=MODEL):
    if "Qwen3" in model:
        model_input += "/no_think"     # non-thinking mode for qwen-3

    data = {
        "model": model,
        "messages": [
            {'role': 'system', 'content': instruction},
            {'role': 'user', 'content': model_input},
        ],
    }

    if "gemini-2.5" in model:
        data['reasoning_effort'] = 'low'   # this is the minimal thinking budget for gemini

    if API_KEY is not None:
        headers = {'Authorization': f'Bearer {API_KEY}', 'Content-Type': 'application/json'}
    else:
        headers = None

    max_retries = 3
    retry_count = 0
    while retry_count < max_retries:
        try:
            response = requests.post(URL, json=data, headers=headers)
            response.raise_for_status()
            model_output = response.json()['choices'][0]['message']['content']
            model_output = model_output.replace('<think>', '').replace('</think>', '').strip()
            return model_output
        except Exception as e:
            retry_count += 1
            if retry_count < max_retries:
                logger.error(f"Error in calculate_similarity_score (attempt {retry_count}/{max_retries}): {e}")
                time.sleep(2)
            else:
                logger.error(f"Error in calculate_similarity_score (final attempt): {e}")
                return None


def calculate_similarity_score(time, question, pred, gold):
    model_input = (
        f"Question: {question}\n"
        f"Ground Truth Answer: {gold}\n"
        f"Predicted Answer: {pred}\n"
    )

    model_output = send_request(model_input, similarity_instruction[MAX_SCORES], model=MODEL)
    if model_output in ['5', '4', '3', '2', '1']:
        score = int(model_output) - 1
    else:
        score = None        # failing requests does not count into the reward
    return time, score


def calculate_is_repetition(time, previous_sents, pred_sent):
    model_input = (
        f"Previous Turns: {previous_sents}\n"
        f"New Turn: {pred_sent}\n"
    )
    model_output = send_request(model_input, repetition_instruction, model=MODEL_REPETITION)
    res = None if model_output is None else model_output.lower().startswith('yes')
    return time, res


def calculate_have_common_prefix(time, previous_sents, pred_sent):
    for prev_sent in previous_sents:
        common_prefix = os.path.commonprefix([prev_sent, pred_sent])
        if len(common_prefix) >= COMMON_PREFIX_THRES:
            return time, 1
    return time, 0


def parse_solution_str(solution_str):
    if not solution_str.startswith('assistant\n'):
        solution_str = 'assistant\n' + solution_str
    if not solution_str.endswith('\nuser'):
        solution_str += '\nuser'

    pattern = r'(?<=assistant\n)(.*?)(?=\nuser|$)'
    responses = re.findall(pattern, solution_str, re.DOTALL)
    return [r.strip() for r in responses]


def area_under_line_ratio(points, max_x, max_y, floor_time_score_weight=0.5, start_score=0.5):
    """
    计算坐标点组成的折线与 x 轴围成的面积
    值得注意的是，这里相邻的两个点并不是直接连一个斜线过去，而是在后一个点x_2处，y值忽然激增到y_2。

    :param points: 列表，包含 (x, y) 元组，例如 [(x1, y1), (x2, y2), ...]
    :return: 面积（浮点数）
    """
    if not len(points): return start_score / max_y
    points = sorted(points, key=lambda p: p[0])  # 按 x 坐标排序（确保从左到右计算）

    # 即使我在span的最后生成回复，也被认定为获得了`floor_time_score_weight=0.5` of all 时间分。
    # 不然的话，如果模型恰好在span的结尾才生成回复，时间分就几乎为0，这导致最终整体分数也几乎为0了。
    # 而这个接近span的结尾才生成的答案显然也是有价值的。``
    # 这个超参数如果是0，则不对横轴进行修改，是timeliness比correctness更重要的情景。
    # 这个超参数如果是1，则将所有点的横轴平移到1。是correctness比timeliness更重要的情景。

    # if floor_time_score_weight == 1: floor_time_score_weight = 0.99     # 为了防止所有点在x轴上重合在一起，并不能真的设定成1，改成0.99就够
    points = [(x * (1 - floor_time_score_weight), y) for x, y in points]
    points.append([max_x, points[-1][1]])
    prev_y, prev_x, area = start_score, 0, 0
    max_area = max_x * max_y
    for i in range(len(points)):
        x1, y1 = points[i]
        area += (x1 - prev_x) * prev_y
        prev_x, prev_y = x1, y1
    return area / max_area


def pauc_reward_function(data_source, solution_str, ground_truth, extra_info=None):
    reply_timestamps = ground_truth['model_pred_timestamps']
    assistant_replies_in_prompt = list(ground_truth.get('prev_assistant_replies', list()))
    max_score = MAX_SCORES - 1
    pred_data = list(zip(reply_timestamps, parse_solution_str(solution_str)))

    # gather the commands that  should be executed
    similarity_args, repetition_args = list(), list()
    if REPETITION_IN_ALL_SPANS:
        added_pred_sents_all_spans = copy.copy(assistant_replies_in_prompt)
        for time, pred_sent in pred_data:
            if pred_sent == NO_REPLY_STR: continue
            if pred_sent in added_pred_sents_all_spans: continue
            added_pred_sents_all_spans.append(pred_sent)
            repetition_args.append((time, ' '.join(added_pred_sents_all_spans[:-1]), pred_sent))

    have_common_prefix = list()
    for sent_i in range(len(pred_data)):
        prev_sents_in_pred_data = [e[1] for e in pred_data[:sent_i]]
        have_common_prefix.append(
            calculate_have_common_prefix(
                pred_data[sent_i][0],  prev_sents_in_pred_data + assistant_replies_in_prompt, pred_data[sent_i][1]))
    reward_common_prefix = -1 * (sum([e[1] for e in have_common_prefix]) / len([e[1] for e in have_common_prefix]) if have_common_prefix else 0)


    inspan_reply_times = set()
    for answer_turn in ground_truth['answer']:
        if answer_turn['reply_timespan'][0] > pred_data[-1][0]:
            # this answer turn is totally truncated as input is too long
            continue
        all_pred_sents = [(time, pred_sent) for time, pred_sent in pred_data \
                    if answer_turn['reply_timespan'][0] <= time <= answer_turn['reply_timespan'][1]]
        inspan_reply_times.update([time for time, _ in all_pred_sents])
        added_pred_sents = []
        points = list()
        for time, pred_sent in all_pred_sents:
            if pred_sent == NO_REPLY_STR: continue
            if pred_sent in added_pred_sents:
                continue

            added_pred_sents.append(pred_sent)

            if PAUC_ADD_PREV_TURNS:
                similarity_args.append((time, answer_turn['question'], ' '.join(added_pred_sents), answer_turn['content']))
            else:
                similarity_args.append((time, answer_turn['question'], pred_sent, answer_turn['content']))

            if not REPETITION_IN_ALL_SPANS and len(added_pred_sents) > 1:
                repetition_args.append((time, ' '.join(added_pred_sents[:-1]), pred_sent))

    # out-of-span replies
    outspan_times = [(time, pred_sent) for time, pred_sent in pred_data if time not in inspan_reply_times]
    outspan_replies = [(time, pred_sent) for time, pred_sent in pred_data if time not in inspan_reply_times and pred_sent != NO_REPLY_STR]
    reward_outspan = -1 * (len(outspan_replies) / len(outspan_times) if outspan_times else 0)

    # execute the commands in parallel
    # DEPRECATED: i moved the parallelism code to verl/verl/workers/reward_manager/naive.py
    # with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
    #     if PAUC_WEIGHT != 0:
    #         similarity_futures = [executor.submit(calculate_similarity_score, *args) for args in similarity_args]
    #     if REPETITION_WEIGHT != 0:
    #        repetition_futures = [executor.submit(calculate_is_repetition, *args) for args in repetition_args]

    #     if PAUC_WEIGHT != 0:
    #         similarity_results = [future.result() for future in concurrent.futures.as_completed(similarity_futures)]
    #         similarity_results_dict = dict(similarity_results)
    #     else:
    #         similarity_results_dict = dict()
    #     if REPETITION_WEIGHT != 0:
    #         repetition_results = [future.result() for future in concurrent.futures.as_completed(repetition_futures)]
    #         repetition_results_dict = dict(repetition_results)
    #     else:
    #         repetition_results_dict = dict()

    if PAUC_WEIGHT != 0:
        similarity_results = [calculate_similarity_score(*args) for args in similarity_args]
        similarity_results_dict = dict(similarity_results)
    else:
        similarity_results_dict = dict()

    if REPETITION_WEIGHT != 0:
        repetition_results = [calculate_is_repetition(*args) for args in repetition_args]
        repetition_results_dict = dict(repetition_results)
    else:
        repetition_results_dict = dict()

    # read the scores from the dict
    auc_list, repetition_list = list(), list()

    if REPETITION_IN_ALL_SPANS:
        added_pred_sents_all_spans = assistant_replies_in_prompt
        for time, pred_sent in pred_data:
            if pred_sent == NO_REPLY_STR: continue
            if pred_sent in added_pred_sents_all_spans:
                repetition_list.append(1)
                continue
            added_pred_sents_all_spans.append(pred_sent)
            if repetition_results_dict.get(time, None) is not None:
                repetition_list.append(repetition_results_dict[time])

    for answer_turn in ground_truth['answer']:
        if answer_turn['reply_timespan'][0] > pred_data[-1][0]:
            # this answer turn is totally truncated as input is too long
            continue
        all_pred_sents = [(time, pred_sent) for time, pred_sent in pred_data \
                    if answer_turn['reply_timespan'][0] <= time <= answer_turn['reply_timespan'][1]]
        added_pred_sents = list()
        points = list()
        for time, pred_sent in all_pred_sents:
            if pred_sent == NO_REPLY_STR: continue

            if not REPETITION_IN_ALL_SPANS and pred_sent in added_pred_sents and REPETITION_WEIGHT != 0:
                repetition_list.append(1)

            if pred_sent in added_pred_sents:
                continue
            added_pred_sents.append(pred_sent)

            score = similarity_results_dict.get(time, None)
            if score is not None:
                points.append((time - answer_turn['reply_timespan'][0], score))

            if len(added_pred_sents) != 1 and repetition_results_dict.get(time, None) is not None:
                repetition_list.append(repetition_results_dict[time])

        max_x, max_y = answer_turn['reply_timespan'][1] - answer_turn['reply_timespan'][0], max_score
        auc_list.append(area_under_line_ratio(points, max_x, max_y))

    reward_auc = sum(auc_list) / len(auc_list) if len(auc_list) else 0
    reward_repetition = -1 * (sum(repetition_list) / len(repetition_list) if len(repetition_list) else 0)

    # random sample 1/10 of the results for debug print
    if hash(ground_truth['question_id']) % 10 == 0:
        print("ground_truth:", ground_truth)
        print('parsed solution:', parse_solution_str(solution_str))
        print('extra_info:', extra_info)
        print(f'{similarity_results_dict=} {repetition_results_dict=} {outspan_times=} {outspan_replies=} {have_common_prefix=}')
        print(f'{reward_auc=} {reward_repetition=} {reward_outspan=} {reward_common_prefix=}')
    return PAUC_WEIGHT * reward_auc + REPETITION_WEIGHT * reward_repetition + \
        OUTSPAN_WEIGHT * reward_outspan + COMMON_PREFIX_WEIGHT * reward_common_prefix


def debug_reward_function(data_source, solution_str, ground_truth, extra_info=None):
    print("ground_truth:", ground_truth)
    print('parsed solution:', parse_solution_str(solution_str))
    print('extra_info:', extra_info)
    return random.random()


def compute_score(*args, **kwargs):
    return pauc_reward_function(*args, **kwargs)


if __name__ == "__main__":
    solution_str = """NO REPLY
user
What activity is the young blonde woman engaged in?
assistant
The young blonde woman is seemingly involved in a conversation or video call.
user

assistant
NO REPLY
user

assistant
NO REPLY
user

assistant
The woman is brushing her teeth with a toothbrush.
user

assistant
The woman is brushing her teeth with a toothbrush, and holding a toothpaste.
user

assistant
NO REPLY
user

assistant
NO REPLY"""

    ground_truth = {
        'answer': [
            # {'content': 'The woman is preparing to brush her teeth by holding a toothpaste and a toothbrush.', 'reply_timespan': [3.44, 9.84], 'question': 'What is the woman doing?'},
            {'content': 'The woman is having a conversation.', 'reply_timespan': [1, 3], 'question': 'What is the woman doing?'},
            {'content': 'The woman is brushing her teeth.', 'reply_timespan': [3, 9], 'question': 'What is the woman doing?'},
        ],
        'question_id': 'd0zI4QDJNA0.63.mp4',
        'model_pred_timestamps': [1, 2, 3, 4, 5, 6, 7, 8],
        'prev_assistant_replies': ['The woman is brushing her teeth with toothbrush.']
    }

    print(parse_solution_str(solution_str))
    print(pauc_reward_function(None, solution_str, ground_truth))
